[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            nixPkgs = [
                "ffmpeg",
                "curl"
            ],
            cmds = [
                "sudo mkdir /tmp/yt_dlp/",
                "sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /tmp/yt_dlp/yt-dlp",
                "sudo chmod a+rx /tmp/yt_dlp/yt-dlp",
                "export PATH=/tmp/yt_dlp:$PATH"
            ]
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
