[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            cmds = [
                "sudo apt-get update",
                "sudo apt-get install -y ffmpeg yt-dlp curl"
            ],
            aptPkgs = [
                "ffmpeg",
                "yt-dlp",
                "curl"
            ]
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
