[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            nixPkgs = [
                "ffmpeg",
                "curl"
            ],
            cmds = [
                "sudo apt update",
                "sudo apt -y install devscripts build-essential debhelper",
                "sudo mkdir /tmp/yt_dlp/",
                "sudo curl -L http://deb.debian.org/debian/pool/main/y/yt-dlp/yt-dlp_2024.11.04-1.dsc -o /tmp/yt_dlp/yt-dlp_2024.11.04-1.dsc",
                "cd /tmp/yt_dlp && dpkg-source -x /tmp/yt_dlp/yt-dlp.dsc",
                "cd /tmp/yt_dlp/yt-dlp && dpkg-buildpackage -us -uc",
                "cd /tmp/yt_dlp && sudo dpkg -i yt-dlp.deb"
            ]
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
