[build]
builder = "NIXPACKS"

[nixpacksPlan]
phases = {
  build = {
    nixPkgs = [
      "yt-dlp"   # Instala o yt-dlp via Nixpkgs
      "ffmpeg"   # Instala o ffmpeg via Nixpkgs
      "curl"     # Instala o curl via Nixpkgs
    ]
  }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
