[build]
builder = "NIXPACKS"

[nixpacksPlan]
phases = {
  install_deps = {
    nixPkgs = [
      "yt-dlp"  # Instalar o yt-dlp via Nixpkgs
      "ffmpeg"  # Instalar o ffmpeg via Nixpkgs
      "curl"    # Instalar o curl via Nixpkgs
    ]
  }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
