[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            cmds = [
                "wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O ~/.local/bin/yt-dlp",
                "chmod a+rx ~/.local/bin/yt-dlp"
            ],
            nixPkgs = [
                "ffmpeg",
                "curl"
            ] 
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
