[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            nixPkgs = [
                "ffmpeg",
                "curl"
            ],
            cmds = [
                "sudo pip install -U yt-dlp"
            ]
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
