[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            nixPkgs = [
                "ffmpeg",
                "curl"
            ],
            cmds = [
                "sudo apt update",
                "sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /opt/yt-dlp",
                "sudo chmod a+rx /opt/yt-dlp",
                "sudo ln -s /opt/yt-dlp /usr/local/bin/yt-dlp"
            ]
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
