[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            nixPkgs = [
                "yt-dlp",
                "ffmpeg",
                "curl"
            ],
            cmds = [
                "curl -L https://github.com/yt-dlp/yt-dlp/releases/download/2024.11.04/yt-dlp_linux -o /usr/local/bin/yt-dlp",
                "chmod +x /usr/local/bin/yt-dlp"
            ]
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
