[build]
builder = "NIXPACKS"
nixpacksPlan = { 
    "phases" = [
        {
            "name" = "install-deps",
            "cmds" = [
                "apt update",
                "apt install -y ffmpeg yt-dlp curl"
            ],
            "aptPkgs" = [
                "ffmpeg",
                "yt-dlp",
                "curl"
            ]
        }
    ]
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
