[build]
builder = "NIXPACKS"

nixpacksPlan = {
    phases = {
        install_deps = {
            cmds = [],
            nixPkgs = [
                "ffmpeg",
                "yt-dlp",
                "curl"
            ]
        }
    }
}

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
